---
- include: merge_vars.yml
  tags:
    - always

- name: Skip if not configured
  meta: end_play
  when: backend.storage != 'graphite'

- include: install_packages.yml
  tags:
    - packages

- include: configure_firewall.yml
  tags:
    - firewall

- include: configure_carbon.yml
  tags:
    - carbon

- include: configure_graphite.yml
  tags:
    - graphite

- name: Reload systemd
  systemd:
    daemon_reload: yes
    # Even when just calling daemon-reload, ansible < 2.4 requires a name for this call
    name: carbon-cache
  tags:
    - packages
    - services

- include: start_services.yml
  tags:
    - services
