---
- name: Service handler
  # We use the systemd module here so we can use the daemon_reload feature,
  # since we're shipping the .service file ourselves
  systemd:
    name: prometheus
    daemon_reload: true
    enabled: true
    state: restarted
