---
- name: Ask GitHub about the most recent release
  # We use local_action here to reduce the amount of times we hit the GitHub
  # API; without it, a moderately-large cluster could actually cause them to
  # invoke their API rate limiting!
  local_action:
    module: uri
    url: https://api.github.com/repos/prometheus/node_exporter/releases/latest
    return_content: true
  connection: local
  become: false
  run_once: true
  register: latest_release

- name: Decide which release to look for
  set_fact:
    os_string: "linux-{{ node_exporter.arch_map[ansible_architecture]|default(ansible_architecture) }}"

- name: Find the correct release
  set_fact:
    release_url: "{{ item.browser_download_url }}"
  when: os_string in item.name
  with_items: "{{ latest_release.json.assets }}"
  no_log: true

- name: Download release
  get_url:
    url: "{{ release_url }}"
    dest: '/tmp/'
  register: download

- name: Extract tarball
  unarchive:
    src: "{{ download.dest }}"
    remote_src: true
    dest: "/tmp/"

- name: Copy binary into place
  copy:
    src: "{{ download.dest|replace('.tar.gz', '') }}/node_exporter"
    remote_src: true
    dest: "/usr/local/sbin/"
    owner: node_exporter
    mode: 0744
