---
- include: merge_vars.yml
  tags:
    - always

- name: End play if no containers are desired
  meta: end_play
  when:
    - not containerized

- include: sanity.yml
  tags:
    - sanity

- include: install_packages.yml
  tags:
    - packages

- include: start_services.yml
  tags:
    - services

- name: Create a network
  docker_network:
    name: "{{ docker.network_name }}"
    driver: bridge
