---
- name: Enable collectd_tcp_network_connect SELinux boolean
  seboolean:
    name: collectd_tcp_network_connect
    state: yes
    persistent: yes

- name: Restore SELinux context of OSD journals
  shell: "restorecon -R -v /var/lib/ceph/osd/*/{journal,block.wal}"
  when: "'osds' in group_names"
  register: restorecon
  changed_when: restorecon.stdout|length != 0
  failed_when: restorecon.rc != 0 and restorecon.rc != 255

- include: selinux_module.yml
  when:
    - devel_mode
