---
- include: merge_vars.yml
  tags:
    - always

- include: sanity.yml
  tags:
    - sanity

- include: setup_container.yml
  when:
    - containerized

- include: setup_repos.yml
  when:
    - not containerized
  tags:
    - packages
    - repos

- include: install_packages.yml
  when: not containerized
  tags:
    - packages

- include: configure_firewall.yml
  tags:
    - firewall

- include: configure_grafana.yml
  tags:
    - grafana

- include: start_services.yml
  tags:
    - services
